spring:
  application:
    name: eureka-client-consumer
server:
  port: 7301
eureka:
  client:
    service-url:
      defaultZone: http://svr2.eureka.jacy.io:7102/eureka/
  instance:
    metadata-map:
      role: consumer

eureka-client-provider:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    ServerListRefreshInterval: 3000
    OkToRetryOnAllOperations: true

