eureka:
  instance:
    hostname: eureka2.jacy.io
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.jacy.io:7101/eureka/
server:
  port: 7102