eureka:
  instance:
    hostname: svr1.eureka.jacy.io
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://svr2.eureka.jacy.io:7102/eureka/
server:
  port: 7101