eureka:
  instance:
    hostname: svr2.eureka.jacy.io
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://svr1.eureka.jacy.io:7101/eureka/
server:
  port: 7102